"""
单词深度内容 batch-4：69 个高频词（词根 / 助记 / 例句 / 搭配）。

口径与 batch-3 一致（见 tools/_add-word-content-batch3.py 的 docstring）：
  - 只写**词源有把握**的词，拿不准的不写——不编一个看起来合理的解释；
  - 四块字段齐全（缺一块，详情页那一块就是空态）；
  - 助记写中国学生真会踩的坑：介词搭配、to do 还是 doing、形近词（precede / proceed、
    infer / imply、enforce / reinforce）、名词动词重音。

本文件只有数据，插入逻辑在 tools/_word_content_insert.py。
用法：python tools/_add-word-content-batch4.py
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _word_content_insert import insert_batch  # noqa: E402

# word: (词根拆解, 词根说明, 助记, [(例句, 译文)], [(搭配, 释义)])
ENTRIES = {
    'enforce': (
        'en-（使）+ force（力量）',
        '使规则带上力量，即强制执行。',
        'enforce 是「强制执行（规定）」，reinforce 是「加强」——前缀不同，别混。',
        [('The school enforces a strict deadline for every assignment.', '学校对每份作业都执行严格的截止时间。')],
        [('enforce a rule', '执行规定')],
    ),
    'engage': (
        'en-（使）+ gage（抵押、承诺）',
        'gage 有「质押、担保」之意；把自己押进去，即参与、投入。',
        'engage in（参与）；be engaged in（正忙于）；engaged 还有「已订婚」。',
        [('Students who engage in discussion remember more.', '参与讨论的学生记得更牢。')],
        [('engage in', '参与')],
    ),
    'ensure': (
        'en-（使）+ sure（确定）',
        '使某事确定下来，即确保。',
        'ensure that…（确保某事）；assure 的宾语必须是人（assure sb. that…）。',
        [('Set a fixed time to ensure that review actually happens.', '固定一个时间，确保复习真的发生。')],
        [('ensure that', '确保')],
    ),
    'estimate': (
        'aestim（估价）',
        '源自拉丁语 aestimare「估价」，即估计、估算。',
        'estimate 后接名词或 that 从句，不接 to do。',
        [('Experts estimate the cost at around two million.', '专家估计成本在两百万左右。')],
        [('estimate the cost', '估算成本')],
    ),
    'evolve': (
        'e-（向外）+ volv（滚、转）',
        'volv 表「滚动」（如 revolve、involve）：向外滚开，即逐渐展开、演变。',
        'evolve from（由……演变而来）；evolve into（演变成）。',
        [('The method evolved from a much older technique.', '这种方法由一种更古老的技术演变而来。')],
        [('evolve into', '演变成')],
    ),
    'exaggerate': (
        'ex-（加强）+ agger（堆积）+ -ate',
        'agger 表「堆」（如 exaggerate 本义「往上堆」），即夸大。',
        'exaggerate 是「说得比事实大」，overstate 是「说得比事实重」。',
        [('The report exaggerates the benefits of the new method.', '报告夸大了新方法的好处。')],
        [('exaggerate the effect', '夸大效果')],
    ),
    'exceed': (
        'ex-（超出）+ ceed（走）',
        'ceed / cess 表「走」（如 proceed、access）：走出界，即超过。',
        'exceed 是及物动词，后面直接接宾语，不加 than。',
        [('The result exceeded all our expectations.', '结果超出了我们所有的预期。')],
        [('exceed expectations', '超出预期')],
    ),
    'exclude': (
        'ex-（向外）+ clud（关闭）',
        'clud / clus 表「关」（如 include、conclude）：关在门外，即排除。',
        'exclude A from B；名词 exclusion 同样接 from。',
        [('Two studies were excluded from the final analysis.', '两项研究被排除在最终分析之外。')],
        [('exclude from', '把……排除在外')],
    ),
    'exert': (
        'ex-（向外）+ sert（加入、施加）',
        'sert 表「加入、排列」（如 insert、assert）：把力量加出去，即施加。',
        'exert influence / pressure on sb.，介词用 on。',
        [('Parents exert a strong influence on reading habits.', '父母对阅读习惯有很大影响。')],
        [('exert influence on', '对……施加影响')],
    ),
    'exhibit': (
        'ex-（向外）+ hibit（拿、持有）',
        'hibit 表「持有」（如 prohibit、inhibit）：拿出来给人看，即展出、表现出。',
        'exhibit 作动词常接「特征、模式」；作名词是「展品」。',
        [('The samples exhibit the same pattern.', '这些样本表现出同样的模式。')],
        [('exhibit a pattern', '表现出某种模式')],
    ),
    'expand': (
        'ex-（向外）+ pand（展开）',
        'pand 表「铺开」（如 expand 本义「摊开」），即扩大、扩张。',
        'expand on sth. 是「就某事展开说明」，不是「扩大某物」。',
        [('The company plans to expand into three new cities.', '公司计划扩张到三座新城市。')],
        [('expand into', '扩展到')],
    ),
    'expend': (
        'ex-（出去）+ pend（称量、支付）',
        'pend / pens 表「称量、付出」（如 compensate、expensive）：称出去，即花费。',
        'expend 多用于时间、精力等正式语境；日常用 spend。',
        [('They expended enormous effort on a single experiment.', '他们在一个实验上投入了巨大精力。')],
        [('expend energy', '耗费精力')],
    ),
    'explicit': (
        'ex-（向外）+ plic（折叠）',
        'plic 表「折」（如 imply、complicate）：把折着的部分摊开，即明确的。',
        'explicit（明说的）对 implicit（隐含的），阅读题常考这对。',
        [('The instructions are explicit about the word limit.', '说明对字数限制讲得很明确。')],
        [('explicit instructions', '明确的指示')],
    ),
    'explore': (
        'ex-（向外）+ plor（探查、呼喊）',
        '源自拉丁语 explorare「搜索、探查」（猎人呼喊着搜寻猎物），即探索。',
        'explore 后可接「问题、可能性」，不一定是真的地理探索。',
        [('The chapter explores how memory actually works.', '这一章探讨记忆究竟如何运作。')],
        [('explore a possibility', '探索可能性')],
    ),
    'expose': (
        'ex-（向外）+ pose（放置）',
        'pos / pon 表「放」（如 propose、expose）：放在外面，即暴露、使接触。',
        'be exposed to 后接「接触到的东西」，to 是介词。',
        [('Children exposed to two languages switch tasks faster.', '接触两种语言的孩子转换任务更快。')],
        [('be exposed to', '接触到')],
    ),
    'extend': (
        'ex-（向外）+ tend（伸展）',
        'tend / tens 表「拉、伸」（如 intend、intense）：向外拉长，即延长。',
        'extend a deadline（延长期限）；extend thanks（致谢）。',
        [('The deadline was extended by two weeks.', '截止日期延长了两周。')],
        [('extend a deadline', '延长期限')],
    ),
    'extract': (
        'ex-（向外）+ tract（拉）',
        'tract 表「拉」（如 attract、abstract）：拉出来，即提取。',
        'extract A from B；名词 extraction 同理。',
        [('Researchers extracted DNA from the samples.', '研究人员从样本中提取了 DNA。')],
        [('extract from', '从……提取')],
    ),
    'fluctuate': (
        'fluct（波动）+ -ate',
        'fluctus 是拉丁语「波浪」，即起伏、波动。',
        'fluctuate between A and B；主语通常是价格、数量、成绩。',
        [('Prices fluctuated wildly during the first quarter.', '第一季度价格剧烈波动。')],
        [('fluctuate between', '在……之间波动')],
    ),
    'formulate': (
        'form（形式、模型）+ -ulate',
        '给想法一个成形的外壳，即制定、系统表述。',
        'formulate 比 make 正式，宾语多是 plan、rule、theory。',
        [('She formulated the rule in one clear sentence.', '她用一句清楚的话把规则表述出来。')],
        [('formulate a plan', '制定计划')],
    ),
    'fulfill': (
        'full（满）+ fill（填满）',
        '两个「满」叠在一起：把要求填满，即实现、履行。',
        'fulfil（英式）与 fulfill（美式）都对，别写成 fullfill。',
        [('The programme fulfils the requirements of most majors.', '这个项目满足多数专业的要求。')],
        [('fulfil a requirement', '满足要求')],
    ),
    'fundamental': (
        'fund（底部、基础）+ -amental',
        'fund 表「基底」（如 fund、found、profound）：打底的，即根本的。',
        'fundamental to 后接名词或 doing，to 是介词。',
        [('Reading is fundamental to every other skill.', '阅读是其他一切技能的根本。')],
        [('fundamental to', '对……至关重要')],
    ),
    'generate': (
        'gener（产生、种类）+ -ate',
        'gen 表「生」（如 gene、genius）：生出来，即产生。',
        'generate 多用于「产生数据、收入、想法」，不用于「制造实物」。',
        [('The model generates a score for each answer.', '模型为每份答案生成一个分数。')],
        [('generate income', '产生收入')],
    ),
    'gradual': (
        'grad（台阶、级）+ -ual',
        'grad 表「步、级」（如 grade、graduate）：一级一级的，即逐渐的。',
        'gradual 强调「慢而有过程」，不用于突然的变化。',
        [('Progress is gradual, but it is still progress.', '进步是渐进的，但它依然是进步。')],
        [('a gradual change', '渐进的变化')],
    ),
    'hypothesis': (
        'hypo-（在下）+ thesis（放置）',
        'thesis 表「放置、命题」（如 thesis、synthesis）：垫在下面的命题，即假说。',
        '复数是 hypotheses，不是 hypothesises。',
        [('The data support the hypothesis rather than disprove it.', '数据支持这个假说，而不是推翻它。')],
        [('test a hypothesis', '检验假说')],
    ),
    'ignore': (
        'i-（= in-，不）+ gnor（知道）',
        'gn / gno 表「知道」（如 know、recognize）：不去知道，即忽视。',
        'ignore 是「明知而有意不理」；be ignorant of 是「压根不知道」。',
        [('Do not ignore the words you keep forgetting.', '别忽略那些你总记不住的词。')],
        [('ignore a warning', '无视警告')],
    ),
    'illustrate': (
        'il-（进入）+ lustr（照亮）',
        'lustr 表「光」（如 illustrate 本义「照亮」）：照亮道理，即说明。',
        'illustrate with 后接「用什么例子说明」。',
        [('Let me illustrate this with a simple example.', '让我用一个简单的例子说明这一点。')],
        [('illustrate with', '用……说明')],
    ),
    'imitate': (
        'im（相像、模仿）+ -itate',
        'im 表「像」（如 image、imitate）：照着样子来，即模仿。',
        'imitate 中性；mimic 常带「滑稽地学样」的意味。',
        [('Children imitate the way adults speak.', '孩子模仿大人说话的方式。')],
        [('imitate a style', '模仿风格')],
    ),
    'immense': (
        'im-（不）+ mens（测量）',
        'mens / meter 表「测量」（如 measure、dimension）：大到量不出来，即巨大的。',
        'immense 修饰程度（an immense amount of），不修饰具体尺寸。',
        [('The change required an immense amount of revision.', '这个改动需要极大量的修订。')],
        [('an immense amount of', '大量的')],
    ),
    'implement': (
        'im-（进入）+ ple（填满）',
        'ple 表「填满」（如 complete、supplement）：把计划填上细节去做，即实施。',
        '名词「工具」和动词「实施」同形，看句子里缺的是「物」还是「动作」。',
        [('The school implemented the new timetable in September.', '学校在九月实施了新的课表。')],
        [('implement a policy', '执行政策')],
    ),
    'impose': (
        'im-（在……上）+ pose（放置）',
        'pos / pon 表「放」（如 compose、oppose）：放到别人身上，即强加。',
        'impose sth. on sb.；impose on sb. 也有「打扰」的意思。',
        [('The rule imposes a heavy burden on new students.', '这条规定给新生带来沉重负担。')],
        [('impose on', '把……强加于')],
    ),
    'impress': (
        'im-（在上）+ press（压）',
        'press 表「压」（如 pressure、compress）：压上印记，即使印象深刻。',
        'be impressed by / with；impress sth. on sb. 是「使某人铭记」。',
        [('She impressed the examiners with a clear structure.', '她以清晰的结构给考官留下印象。')],
        [('be impressed by', '对……印象深刻')],
    ),
    'incentive': (
        'in-（进入）+ cant（歌唱）+ -ive',
        'cant / cent 表「唱」（如 chant、accent）：原指「唱歌招徕、激励」，即动机、激励。',
        'an incentive to do sth.；tax incentive 是「税收优惠」。',
        [('Small rewards give students an incentive to keep going.', '小小的奖励给学生继续下去的动力。')],
        [('an incentive to', '……的动力')],
    ),
    'incline': (
        'in-（朝向）+ clin（倾斜）',
        'clin 表「倾斜」（如 decline、climate）：朝某方向倾斜，即倾向。',
        'be inclined to do sth.（倾向于），to 是不定式符号。',
        [('Examiners are inclined to reward clear structure.', '考官往往会给结构清晰的答案更高分。')],
        [('be inclined to', '倾向于')],
    ),
    'incorporate': (
        'in-（进入）+ corpor（身体）+ -ate',
        'corpor 表「身体」（如 corporation）：纳入同一个身体，即包含、合并。',
        'incorporate A into B；形容词 incorporated 常缩写为 Inc.（公司）。',
        [('The final version incorporates three of her suggestions.', '最终版本吸收了她的三条建议。')],
        [('incorporate into', '并入')],
    ),
    'induce': (
        'in-（向内）+ duc（引导）',
        'duc 表「引导」（如 conduct、deduce）：引导进来，即引起、诱导。',
        'induce sb. to do sth.（劝使）；induce a change（引起变化）。',
        [('Poor sleep induces errors even in simple tasks.', '睡眠不足连简单任务都会出错。')],
        [('induce a change', '引起变化')],
    ),
    'inevitable': (
        'in-（不）+ evit（避免）+ -able',
        'evit 表「躲开」（与 avoid 同源）：躲不开的，即不可避免的。',
        'It is inevitable that…；注意 inevitable 没有「必然正确」的意思。',
        [('Some forgetting is inevitable; review is the answer.', '遗忘不可避免，复习才是解药。')],
        [('it is inevitable that', '……不可避免')],
    ),
    'infer': (
        'in-（向内）+ fer（带来）',
        'fer 表「携带」（如 refer、transfer）：把意思带进来，即推断。',
        'infer（读者推断出）对 imply（作者暗示）——阅读题高频考点。',
        [('From the tone we can infer that the author disagrees.', '从语气可以推断作者不同意。')],
        [('infer from', '从……推断')],
    ),
    'inherit': (
        'in-（在内）+ her（继承人）',
        'her 表「继承」（如 heritage、heir）：接过来成为自己的，即继承。',
        'inherit sth. from sb.；计算机语境里指「继承父类特性」。',
        [('The system inherits several features from the old design.', '这个系统继承了旧设计的若干特性。')],
        [('inherit a feature', '继承特性')],
    ),
    'initiate': (
        'in-（进入）+ it（走）+ -iate',
        'it 表「走」（如 initial、exit）：走进去开头，即发起、开始。',
        'initiate 比 start 正式，宾语多是 programme、talks、process。',
        [('She initiated a weekly review session for the class.', '她为班级发起了一个每周一次的复习。')],
        [('initiate a programme', '启动项目')],
    ),
    'install': (
        'in-（在内）+ stall（位置）',
        'stall 表「位置、摊位」（如 stall）：放到位置上安置好，即安装、安置。',
        'install software（装软件）；install sb. in office（使就职）。',
        [('Install the app before the first class.', '第一次课前装好这个应用。')],
        [('install software', '安装软件')],
    ),
    'institute': (
        'in-（在上）+ stit（设立、站立）',
        'stit 表「设立」（如 constitute、substitute）：立起来，即设立、制定。',
        'institute 是动词「设立」；institution 是名词「机构/制度」。',
        [('The university instituted a new reading requirement last year.', '这所大学去年设立了新的阅读要求。')],
        [('institute a rule', '制定规则')],
    ),
    'insulate': (
        'insul（岛屿）+ -ate',
        'insula 是拉丁语「岛」：变成孤岛，即隔离、使隔绝。',
        'insulate A from B（使 A 免受 B 影响）；物理义是「绝缘」。',
        [('Good habits insulate you from last-minute panic.', '好习惯能让你免于临考前的慌乱。')],
        [('insulate from', '使免于')],
    ),
    'integrate': (
        'integer（完整、未触碰）',
        'in-（不）+ tang（触碰）：没被碰破的、完整的，即使成一体、整合。',
        'integrate A into / with B；形容词 integrated 是「融合的」。',
        [('Try to integrate new words into sentences you actually use.', '试着把新词用到你真会说的句子里。')],
        [('integrate into', '融入')],
    ),
    'intense': (
        'in-（加强）+ tens（拉紧）',
        'tend / tens 表「拉」（如 extend、tension）：拉到很紧，即强烈的。',
        'intense 修饰「程度高」的事物（heat、pressure、competition）。',
        [('Intense revision works only if you sleep enough.', '只有睡够了，高强度复习才有效。')],
        [('intense pressure', '巨大的压力')],
    ),
    'interpret': (
        'inter-（在……之间）+ pret（传递、价值）',
        '在双方之间传话，于是有了「口译」与「解释」两义。',
        'interpret A as B（把 A 理解为 B）；口译员也叫 interpreter。',
        [('Different readers interpret the ending differently.', '不同读者对结尾有不同解读。')],
        [('interpret as', '把……理解为')],
    ),
    'intervene': (
        'inter-（在……之间）+ ven（来）',
        'ven / vent 表「来」（如 prevent、event）：来到中间，即干预、介入。',
        'intervene in sth.（介入某事）；名词 intervention。',
        [('Teachers intervened before the gap widened.', '差距扩大之前，老师就介入了。')],
        [('intervene in', '干预')],
    ),
    'isolate': (
        'isol（岛屿）+ -ate',
        '与 insulate 同源：变成一座岛，即孤立、隔离。',
        'isolate A from B；实验语境里指「把变量单独拿出来」。',
        [('Isolate the variable you want to test.', '把你要检验的变量单独隔离出来。')],
        [('isolate from', '把……与……隔离')],
    ),
    'justify': (
        'just（公正）+ -ify（使……化）',
        '使变得正当，即证明……有理、为……辩护。',
        'justify doing sth.（不接 to do）；排版里「两端对齐」也是这个词。',
        [('Nothing justifies skipping the review session.', '没有什么能为跳过复习开脱。')],
        [('justify a decision', '为决定辩护')],
    ),
    'manipulate': (
        'man（手）+ pul（填充、操作）+ -ate',
        'man 表「手」（如 manual、manufacture）：用手摆弄，即操作、操纵。',
        'manipulate 作「操纵」时多带贬义（manipulate data / public opinion）。',
        [('The study manipulated two variables at a time.', '该研究一次操纵两个变量。')],
        [('manipulate data', '操纵数据')],
    ),
    'motivate': (
        'mot（移动）+ -ivate',
        'mot / mov 表「动」（如 motion、move）：让人动起来，即激励。',
        'motivate sb. to do sth.；名词 motivation 常与 lose / lack 搭配。',
        [('Clear progress motivates students more than praise.', '明确的进步比表扬更能激励学生。')],
        [('motivate sb. to', '激励某人做')],
    ),
    'negotiate': (
        'neg-（不）+ oti（闲暇）',
        'negotium 本是「没有闲暇（即忙于事务）」，后指「谈生意、协商」。',
        'negotiate with sb. over / for sth.；不加 about。',
        [('They negotiated a longer deadline with the supervisor.', '他们和导师谈成了更长的期限。')],
        [('negotiate with', '与……协商')],
    ),
    'occupy': (
        'oc-（= ob-，朝向）+ cup（抓取）',
        'cap / cup 表「抓、拿」（如 capture、accept）：抓住不放，即占据、占用。',
        'be occupied with sth.（忙于某事）；occupy 不用于进行时被动。',
        [('Revision occupies most of my weekends.', '复习占了我周末的大部分时间。')],
        [('occupy a position', '占据位置')],
    ),
    'occur': (
        'oc-（朝向）+ cur（跑）',
        'cur / curs 表「跑」（如 current、recur）：跑过来出现，即发生。',
        'occur 没有被动语态；it occurs to sb. that… 是「某人想到」。',
        [('The same error occurs in three of her essays.', '同样的错误在她三篇作文里出现。')],
        [('occur to', '被想到')],
    ),
    'oppose': (
        'op-（= ob-，相对）+ pose（放置）',
        'pos / pon 表「放」（如 propose、expose）：放在对立面，即反对。',
        'be opposed to 里 to 是介词，后接 doing，不是 to do。',
        [('She opposed changing the exam format.', '她反对改变考试形式。')],
        [('oppose a plan', '反对计划')],
    ),
    'participate': (
        'part（部分）+ cip（取）+ -ate',
        'cip / cap 表「拿」（如 accept、anticipate）：拿走一份，即参与。',
        'participate in，不加 to；名词 participation 也接 in。',
        [('Students who participate in class retain more.', '课上参与的学生记得更多。')],
        [('participate in', '参与')],
    ),
    'persuade': (
        'per-（彻底）+ suad（劝说）',
        'suad / suas 表「劝」（如 persuasion、dissuade）：劝到对方点头，即说服。',
        'persuade sb. to do / into doing；劝阻是 dissuade sb. from doing。',
        [('No one persuaded him to change his method.', '没人说服他改变方法。')],
        [('persuade sb. to', '说服某人做')],
    ),
    'precede': (
        'pre-（在前）+ cede（走）',
        'ced / cess 表「走」（如 proceed、exceed）：走在前面，即先于。',
        'precede（先于）与 proceed（继续）只差一个字母，写作时最易写混。',
        [('A short outline precedes the main argument.', '主要论证之前有一段简短提纲。')],
        [('precede with', '以……开头')],
    ),
    'precise': (
        'pre-（预先）+ cis（切）',
        'cis / cid 表「切」（如 decide、concise）：预先切得整齐，即精确的。',
        'precise 强调「分毫不差」，accurate 强调「与事实相符」。',
        [('Give precise figures, not rounded ones.', '给出精确数字，不要取整。')],
        [('precise figures', '精确的数字')],
    ),
    'prefer': (
        'pre-（在前）+ fer（携带）',
        'fer 表「带」（如 refer、transfer）：优先带到前面，即更喜欢。',
        'prefer doing A to doing B；prefer to do rather than do。',
        [('Most learners prefer short sessions to long ones.', '多数学习者宁可短学多次，也不要一次学很久。')],
        [('prefer A to B', '比起 B 更喜欢 A')],
    ),
    'prejudice': (
        'pre-（预先）+ judic（判断）',
        'judic 表「判断」（如 judge、judicial）：在了解之前就下了判断，即偏见。',
        'prejudice against（对……的偏见）；without prejudice to（不影响）。',
        [('Prejudice against new methods slows everything down.', '对新方法的偏见让一切都变慢。')],
        [('prejudice against', '对……的偏见')],
    ),
    'premise': (
        'pre-（在前）+ mis（送、放）',
        'mit / mis 表「送」（如 promise、submit）：先送出来的那句话，即前提。',
        'on the premise that…（在……前提下）；注意与 premises（房屋）区分。',
        [('The whole argument rests on a single premise.', '整个论证建立在一个前提上。')],
        [('on the premise that', '在……前提下')],
    ),
    'prevail': (
        'pre-（在前）+ vail（力量）',
        'val / vail 表「强、有价值」（如 value、valid）：力量占先，即盛行、获胜。',
        'prevail over（胜过）；prevail on sb.（说服某人）。',
        [('Common sense prevailed over the original plan.', '常识最终胜过了原定计划。')],
        [('prevail over', '战胜／压过')],
    ),
    'proceed': (
        'pro-（向前）+ ceed（走）',
        'ceed / cess 表「走」（如 exceed、access）：往前走，即继续进行。',
        'proceed to do / proceed with sth.；名词 process 与它不同源但同源族。',
        [('Once the outline is ready, proceed to the first draft.', '提纲一准备好，就继续写初稿。')],
        [('proceed with', '继续进行')],
    ),
    'prohibit': (
        'pro-（在前）+ hibit（持有）',
        'hibit 表「持有」（如 exhibit、inhibit）：在前面拦住不让你持有，即禁止。',
        'prohibit sb. from doing；名词 prohibition 也接 against。',
        [('The rules prohibit students from using phones in class.', '规定禁止学生在课堂上使用手机。')],
        [('prohibit from', '禁止做')],
    ),
    'provoke': (
        'pro-（向前）+ vok（呼喊）',
        'voc / vok 表「声音、叫」（如 advocate、vocal）：朝前喊出来，即激起、引发。',
        'provoke 多接 reaction、discussion、anger，常带负面结果。',
        [('His question provoked a long discussion.', '他的问题引发了一场长讨论。')],
        [('provoke a reaction', '引起反应')],
    ),
    'qualify': (
        'qual（性质、种类）+ -ify（使……化）',
        'qual 表「什么样」（如 quality）：使具备某种性质，即取得资格。',
        'qualify for（有资格获得）；qualify as（取得……资格）。',
        [('Two more credits qualify you for the advanced class.', '再修两个学分你就有资格上高级班。')],
        [('qualify for', '有资格获得')],
    ),
    'reinforce': (
        're-（再）+ in-（使）+ force（力量）',
        '再次给它加上力量，即加强、强化。',
        'reinforce 是「加强」，enforce 是「强制执行」——前缀决定意思。',
        [('Weekly tests reinforce what you revised on Sunday.', '每周测验能强化你周日复习的内容。')],
        [('reinforce a habit', '强化习惯')],
    ),
    'sustain': (
        'sus-（= sub-，在下）+ tain（握住）',
        'tain 表「拿住」（如 maintain、retain）：在下面托住，即维持、支撑。',
        'sustain 强调「长时间撑住」，maintain 强调「保持原状」。',
        [('Few students sustain that pace for a whole term.', '很少有学生能整个学期保持那个节奏。')],
        [('sustain growth', '维持增长')],
    ),
    'tolerate': (
        'toler（忍受、承担）+ -ate',
        '源自拉丁语 tolerare「承受、忍耐」，即容忍、容许。',
        'tolerate 后接名词或 doing，不接 to do。',
        [('The system tolerates small errors but not big ones.', '这个系统容许小错误，但不能有大错。')],
        [('tolerate errors', '容许错误')],
    ),
}

if __name__ == '__main__':
    insert_batch(ENTRIES, 'batch-4', '高频词第三批（动词与学术常用词）')
