"""
单词深度内容 batch-5：66 个高频词（词根 / 助记 / 例句 / 搭配）。

口径与前两批一致：词源有把握才写；四块字段齐全；助记写中国学生真会踩的坑
（remain 没有进行时、be supposed to、superior to 不用 than、unique 无比较级、
succeed in doing、resist 后接 doing、revise 在英式英语里就是「复习」等）。

本文件只有数据，插入逻辑在 tools/_word_content_insert.py。
用法：python tools/_add-word-content-batch5.py
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _word_content_insert import insert_batch  # noqa: E402

# word: (词根拆解, 词根说明, 助记, [(例句, 译文)], [(搭配, 释义)])
ENTRIES = {
    'react': (
        're-（反）+ act（做）',
        'act 表「做、行动」（如 action、active）：反过来做，即反应。',
        'react to（对……作出反应）；react against（反抗）。',
        [('Readers react strongly to an unclear thesis.', '读者对含糊的中心论点反应强烈。')],
        [('react to', '对……作出反应')],
    ),
    'recall': (
        're-（回）+ call（叫）',
        '把记忆叫回来，即回忆、回想。',
        'recall 后接名词或 doing，不接 to do（recall seeing it）。',
        [('Few students recall the words they only read once.', '只读过一遍的词，很少有学生想得起来。')],
        [('recall doing', '记得做过')],
    ),
    'recover': (
        're-（回）+ cover（取得、覆盖）',
        '重新拿回来，即恢复、找回。',
        'recover from（从……中恢复）；recover 自己恢复，不说 recover sb.。',
        [('She recovered from a bad first mock exam.', '她从一次糟糕的模考中恢复过来。')],
        [('recover from', '从……恢复')],
    ),
    'recruit': (
        're-（再）+ cresc（生长）',
        'cresc / cret 表「生长」（如 increase、concrete）：让队伍重新长起来，即招募。',
        'recruit 的宾语可以是「人」，也可以是「成员、志愿者」。',
        [('The lab recruits ten assistants every spring.', '实验室每年春天招十名助理。')],
        [('recruit staff', '招募人员')],
    ),
    'refer': (
        're-（回）+ fer（带）',
        'fer 表「携带」（如 transfer、infer）：把话题带回去，即提到、参考。',
        'refer to（提到 / 查阅）；refer sb. to（把某人介绍给……）。',
        [('The author refers to two earlier studies.', '作者提到了两项早前的研究。')],
        [('refer to', '提到／查阅')],
    ),
    'refine': (
        're-（反复）+ fin（完成、边界）',
        'fin 表「界限、完成」（如 define、final）：反复打磨到边界，即精炼、改进。',
        'refine 强调「在原基础上改好」，不是推倒重来。',
        [('Refine your outline before you start writing.', '动笔前先把提纲打磨好。')],
        [('refine a method', '改进方法')],
    ),
    'regulate': (
        'reg（引导、统治）+ -ulate',
        'reg 表「引导、管」（如 region、regime）：按规则引导，即管理、调节。',
        'regulate 多用于「机制、生理、市场」的自我调节。',
        [('Sleep regulates how well you retain new words.', '睡眠调节你对新词的记忆效果。')],
        [('regulate a process', '规范流程')],
    ),
    'remain': (
        're-（向后）+ main（停留）',
        'main 源自拉丁语 manere「留下」：留在原处，即仍然是、剩余。',
        'remain 是系动词，不接宾语，也没有进行时（不说 is remaining）。',
        [('Three chapters remain unread.', '还有三章没读。')],
        [('remain silent', '保持沉默')],
    ),
    'remove': (
        're-（离开）+ move（移动）',
        '移开、拿走，即移除。',
        'remove A from B；remove 比 delete 正式，也可指「免职」。',
        [('Remove the sentences that repeat your point.', '删掉那些重复论点的句子。')],
        [('remove from', '从……移除')],
    ),
    'renew': (
        're-（再）+ new（新）',
        '使重新变新，即续借、更新、恢复。',
        'renew a book（续借图书）；renew effort（重新发力）。',
        [('Renew your notes the day after each class.', '每堂课后第二天更新笔记。')],
        [('renew a subscription', '续订')],
    ),
    'reproduce': (
        're-（再）+ produce（生产）',
        '再次生产出来，即复制、再现；生物语境指繁殖。',
        'reproduce 在论文里常指「结果可复现」。',
        [('Try to reproduce the result with a second sample.', '试着用第二份样本复现这个结果。')],
        [('reproduce a result', '复现结果')],
    ),
    'reserve': (
        're-（回）+ serv（保持）',
        'serv 表「保持」（如 preserve、conserve）：留着不用，即保留、预订。',
        'reserve 是「预留/预订」；preserve 是「保存、保护」，别混。',
        [('Reserve the last hour of the day for review.', '把一天最后一小时留给复习。')],
        [('reserve for', '为……保留')],
    ),
    'resist': (
        're-（反）+ sist（站立）',
        'sist 表「站」（如 persist、insist）：站在对立面，即抵抗。',
        'resist 后接名词或 doing：resist checking your phone。',
        [('Resist reading the passage before the question.', '忍住别先读文章，先看题。')],
        [('resist the urge to', '忍住想……')],
    ),
    'resolve': (
        're-（彻底）+ solv（松开）',
        'solv 表「松开、解开」（如 solve、dissolve）：把结解开，即解决、下决心。',
        'resolve to do（下定决心做）；resolve a problem（解决问题）。',
        [('She resolved to review thirty words every morning.', '她下定决心每天早晨复习三十个词。')],
        [('resolve a conflict', '化解冲突')],
    ),
    'restrict': (
        're-（加强）+ strict（拉紧）',
        'strict 表「拉紧」（如 strict、constrain）：拉紧到一定范围，即限制。',
        'restrict A to B（把 A 限制在 B 之内）。',
        [('Restrict each paragraph to one idea.', '每段只讲一个意思。')],
        [('restrict to', '限定在')],
    ),
    'reverse': (
        're-（回）+ vers（转）',
        'vers / vert 表「转」（如 convert、diverse）：转回去，即反转、撤销。',
        'reverse a decision（撤销决定）；in reverse order（倒序）。',
        [('One careless week can reverse a month of progress.', '一周的疏忽能让一个月的进展倒退。')],
        [('reverse a decision', '撤销决定')],
    ),
    'revise': (
        're-（再）+ vis（看）',
        'vis / vid 表「看」（如 review、evident）：再看一遍，即修订、复习。',
        '英式英语里 revise 就是「复习」，美式更常说 review。',
        [('Revise the words you got wrong, not the whole list.', '复习你做错的词，而不是整张表。')],
        [('revise for', '为……复习')],
    ),
    'rigid': (
        'rig（僵硬、伸直）',
        'rig 表「僵硬」（如 rigid 本义「僵直的」）：僵住的，即严格的、死板的。',
        'rigid 多带贬义（死板）；strict 可褒可贬。',
        [('A rigid timetable breaks on the first bad day.', '死板的计划表在第一个糟糕的日子就崩了。')],
        [('rigid rules', '死板的规定')],
    ),
    'satisfy': (
        'satis（足够）+ -fy（使）',
        '使足够，即满足、使满意。',
        'be satisfied with（对……满意）；satisfy a requirement（满足要求）。',
        [('One example rarely satisfies a strict examiner.', '一个例子很难让严格的考官满意。')],
        [('satisfy a requirement', '满足要求')],
    ),
    'secure': (
        'se-（分开）+ cur（担心、照料）',
        'cur 表「关心」（如 cure、accurate）：无需担心，即安全的；作动词「争取到」。',
        'secure 形容词「安全的」，动词「（好不容易）争取到」。',
        [('Secure a quiet desk before you start.', '开始前先占一张安静的桌子。')],
        [('secure a place', '争取到位置')],
    ),
    'select': (
        'se-（分开）+ lect（挑选）',
        'lect 表「选、读」（如 collect、elect）：挑出来，即选择。',
        'select 比 choose 正式；select from 后接「从哪个范围里挑」。',
        [('Select twenty words you keep forgetting.', '挑出二十个你总记不住的词。')],
        [('select from', '从……中挑选')],
    ),
    'sequence': (
        'sequ（跟随）+ -ence',
        'sequ / secut 表「跟随」（如 consequence、subsequent）：一个跟一个，即顺序。',
        'in sequence（按顺序）；sequence of tenses 是「时态一致」。',
        [('Learn the words in the sequence they appear.', '按出现的顺序学这些词。')],
        [('in sequence', '按顺序')],
    ),
    'severe': (
        'sever（严肃、严格）',
        'severus 是拉丁语「严格的」，即严厉的、严重的。',
        'severe 修饰「程度重」：severe shortage、severe weather、severe pain。',
        [('A severe cold cost her two weeks of revision.', '一场重感冒让她丢了两周复习时间。')],
        [('severe shortage', '严重短缺')],
    ),
    'simulate': (
        'simul（相似）+ -ate',
        'simul 表「相同、相似」（如 similar、simultaneous）：做得像真的，即模拟。',
        'simulate 强调「仿照真实过程」，imitate 只是「学样」。',
        [('The program simulates a real exam room.', '这个程序模拟真实考场。')],
        [('simulate a situation', '模拟情境')],
    ),
    'solve': (
        'solv（松开、解开）',
        '把缠住的结解开，即解决。',
        'solve a problem（解题）；resolve 更强调「彻底化解矛盾」。',
        [('Solve the easiest question first to warm up.', '先做最简单的题热热身。')],
        [('solve a problem', '解决问题')],
    ),
    'specify': (
        'speci（种类、看）+ -fy（使）',
        'spec 表「看、种类」（如 specific、species）：一件件看清楚，即明确说明。',
        'specify 后接名词或 that 从句，不接 to do。',
        [('Specify how many words you will review each day.', '明确说明你每天要复习多少词。')],
        [('specify a number', '明确数字')],
    ),
    'sponsor': (
        'spons（承诺、担保）',
        'spons 表「承诺」（如 respond、responsible）：作出承诺支持，即赞助、主办。',
        'sponsor 既能指「出钱的赞助方」，也能指「提案的发起人」。',
        [('The department sponsored her field study.', '系里资助了她的实地研究。')],
        [('sponsor a project', '赞助项目')],
    ),
    'stimulate': (
        'stimul（刺棒、刺激）+ -ate',
        'stimulus 本义是「赶牲口的刺棒」，刺激一下就动起来，即激发。',
        'stimulate interest / growth / discussion。',
        [('Short quizzes stimulate recall better than re-reading.', '小测验比重读更能唤起回忆。')],
        [('stimulate interest', '激发兴趣')],
    ),
    'submit': (
        'sub-（自下）+ mit（送）',
        'mit / miss 表「送」（如 admit、transmit）：从下往上送，即提交、服从。',
        'submit sth. to sb.（提交）；submit to sb.（屈服于）。',
        [('Submit the draft at least a day early.', '至少提前一天交初稿。')],
        [('submit an essay', '提交作文')],
    ),
    'subsequent': (
        'sub-（下面、之后）+ sequ（跟随）',
        'sequ 表「跟随」（如 sequence、consequence）：跟在后面的，即随后的。',
        'subsequent to 是正式说法，写作里可用 after 代替。',
        [('Subsequent chapters build on this one.', '后续章节建立在这一章之上。')],
        [('subsequent to', '在……之后')],
    ),
    'succeed': (
        'suc-（= sub-，自下）+ ceed（走）',
        'ceed / cess 表「走」（如 proceed、exceed）：一路走下去成了，即成功；也指继承。',
        'succeed in doing（成功做成）；succeed to the throne（继承王位）。',
        [('She succeeded in finishing the whole list.', '她成功背完了整张表。')],
        [('succeed in doing', '成功做成')],
    ),
    'supplement': (
        'sup-（= sub-，自下）+ ple（填满）',
        'ple 表「填满」（如 complete、implement）：从下面补满，即补充。',
        'supplement A with B；名词 supplement to（……的增补）。',
        [('Supplement the textbook with one short article.', '用一篇短文补充教材内容。')],
        [('supplement with', '用……补充')],
    ),
    'suppose': (
        'sup-（= sub-，在下）+ pose（放置）',
        'pos / pon 表「放」（如 propose、oppose）：把话放在下面作基础，即假设、认为。',
        'be supposed to（应该）；suppose 一般不用于进行时。',
        [('You are supposed to review before the next class.', '你应该在下节课前复习。')],
        [('be supposed to', '应该')],
    ),
    'suppress': (
        'sup-（= sub-，在下）+ press（压）',
        'press 表「压」（如 pressure、impress）：往下压住，即压制、抑制。',
        'suppress 强调「强行压下去」，repress 多用于心理。',
        [('Do not suppress the questions that confuse you.', '别把你困惑的问题压下去。')],
        [('suppress a feeling', '抑制情绪')],
    ),
    'symbol': (
        'sym-（共同）+ bol（投掷）',
        'symbolon 本是「分成两半的信物」，合起来验证身份，引申为符号、象征。',
        'a symbol of（……的象征）；symbol for（……的记号）。',
        [('A tick is the symbol for a checked answer.', '对勾是已核对答案的记号。')],
        [('a symbol of', '……的象征')],
    ),
    'sympathy': (
        'sym-（共同）+ path（感受）',
        'path 表「感受」（如 sympathy、pathetic）：共同感受，即同情、共鸣。',
        'sympathy for / with sb.；动词是 sympathize with。',
        [('She had little sympathy for last-minute excuses.', '她对临阵磨枪的借口没什么同情。')],
        [('sympathy for', '对……的同情')],
    ),
    'synthesis': (
        'syn-（共同）+ thesis（放置）',
        'thesis 表「放置、命题」（如 hypothesis）：把各家说法放到一起，即综合。',
        'synthesis（综合）对 analysis（分析），阅读题常成对出现。',
        [('The final chapter offers a synthesis of both views.', '最后一章对两种观点作了综合。')],
        [('a synthesis of', '……的综合')],
    ),
    'temporary': (
        'tempor（时间）+ -ary',
        'tempor 表「时间」（如 contemporary）：只管一段时间的，即暂时的。',
        'temporary 对 permanent；缩写 temp 也指「临时工」。',
        [('A timetable is temporary; the habit is permanent.', '计划表是临时的，习惯才长久。')],
        [('a temporary solution', '权宜之计')],
    ),
    'terminate': (
        'termin（边界、终点）+ -ate',
        'termin 表「界限」（如 terminal、determine）：走到边界，即终止。',
        'terminate 是正式用语，日常用 end 或 stop。',
        [('The contract terminates at the end of June.', '合同六月底终止。')],
        [('terminate a contract', '终止合同')],
    ),
    'testify': (
        'test（证人）+ -ify（使）',
        'testis 是拉丁语「证人」：以证人身份说话，即作证、证明。',
        'testify to sth.（表明/证明）；testify against sb.（作不利证词）。',
        [('Two witnesses testified at the hearing.', '两名证人在听证会上作证。')],
        [('testify to', '证明／表明')],
    ),
    'transfer': (
        'trans-（跨越）+ fer（带）',
        'fer 表「携带」（如 refer、infer）：从这里带到那里，即转移、转学。',
        '名词重音在前 /ˈtrænsfɜː/，动词在后 /trænsˈfɜː/。',
        [('Transfer your notes into one notebook.', '把笔记都转到一个本子上。')],
        [('transfer to', '转移到')],
    ),
    'transmit': (
        'trans-（跨越）+ mit（送）',
        'mit 表「送」（如 submit、admit）：送过去，即传输、传播。',
        'transmit 多用于信号、数据、疾病；carry 更泛。',
        [('The device transmits data every ten seconds.', '这个设备每十秒传一次数据。')],
        [('transmit information', '传输信息')],
    ),
    'ultimate': (
        'ultim（最后）+ -ate',
        'ultimus 是拉丁语「最后的」，即最终的、根本的。',
        'the ultimate goal（最终目标）；ultimately（最终）。',
        [('The ultimate goal is recall, not recognition.', '最终目标是能回忆，而不是看着眼熟。')],
        [('the ultimate goal', '最终目标')],
    ),
    'undergo': (
        'under（在……之下）+ go（走）',
        '在下面走一遭，即经历、接受（变化、治疗）。',
        'undergo 是及物，直接接宾语，不加 with。',
        [('The course underwent a full rewrite last year.', '这门课去年经历了一次全面重写。')],
        [('undergo a change', '经历变化')],
    ),
    'uniform': (
        'uni-（单一）+ form（形状）',
        'form 表「形状」（如 reform、transform）：一个形状，即统一的；也指制服。',
        'uniform 作形容词「一致的」，作名词「制服」。',
        [('The format is uniform across all three papers.', '三份试卷的格式是统一的。')],
        [('a uniform standard', '统一标准')],
    ),
    'unique': (
        'uni-（单一）+ -que',
        'unus 是拉丁语「一」：只有一个，即独特的。',
        'unique to（为……所独有）；unique 本身就含「最」，没有 more unique。',
        [('This error is unique to beginners.', '这个错误是初学者特有的。')],
        [('unique to', '为……独有')],
    ),
    'utilize': (
        'uti（使用）+ -ize',
        'uti 表「用」（如 utility、use）：拿来用，即利用。',
        'utilize 比 use 正式，写作里可用来避免重复；别滥用。',
        [('Utilize the five minutes before class for a quick review.', '利用课前五分钟快速复习。')],
        [('utilize resources', '利用资源')],
    ),
    'vary': (
        'vari（变化）',
        'varius 是拉丁语「多样的」，即变化、不同。',
        'vary from A to B / vary with；形容词 various，名词 variety。',
        [('Scores vary from class to class.', '各班分数不一样。')],
        [('vary from', '因……而异')],
    ),
    'verify': (
        'ver（真实）+ -ify（使）',
        'ver 表「真实」（如 very、verdict）：确认为真，即核实。',
        'verify 是「查证是否属实」，confirm 是「确认已定之事」。',
        [('Verify every figure before you quote it.', '引用前核实每一个数字。')],
        [('verify a figure', '核实数字')],
    ),
    'vital': (
        'vit（生命）+ -al',
        'vita 是拉丁语「生命」（如 vitamin、vivid）：关乎生命的，即至关重要的。',
        'vital to / for；It is vital that… 后接 (should) do。',
        [('Sleep is vital to memory.', '睡眠对记忆至关重要。')],
        [('vital to', '对……至关重要')],
    ),
    'violate': (
        'viol（力量、暴力）+ -ate',
        'violare 本义「以强力对待」，即违反、侵犯。',
        'violate a rule / law / agreement；violation 是名词。',
        [('Do not violate the word limit in the summary.', '摘要不要超出字数限制。')],
        [('violate a rule', '违反规定')],
    ),
    'virtual': (
        'virt（力量、德行）+ -ual',
        'virtus 本义「力量、效能」：实质上具有那种力量，即事实上的；也指虚拟的。',
        'virtual 两义都要认识：「虚拟的」与「实质上的（ virtually = 几乎）」。',
        [('The two versions are virtually identical.', '两个版本几乎完全一样。')],
        [('virtually impossible', '几乎不可能')],
    ),
    'radical': (
        'radic（根）+ -al',
        'radix 是拉丁语「根」（如 radish、eradicate）：动到根上，即根本的、激进的。',
        'radical 可褒可贬：radical reform（彻底的改革）／radical idea（激进的想法）。',
        [('A radical change of method rarely helps in exam week.', '考前一周大改方法很少有帮助。')],
        [('a radical change', '根本性的改变')],
    ),
    'ratio': (
        'rat（计算、判断）',
        'reri 是拉丁语「计算、认为」，算出来的比，即比率。',
        'the ratio of A to B（A 与 B 之比）；rate 是「速率/比率」，别混。',
        [('The ratio of new words to reviews is about one to two.', '新词与复习词的比例约为一比二。')],
        [('the ratio of A to B', 'A 与 B 之比')],
    ),
    'quote': (
        'quot（多少）',
        'quot 表「多少、第几」（如 quota、quotient）：按编号引述原文，即引用。',
        'quote 是「照原话引」，cite 是「举出出处」，两者不同。',
        [('She quotes two lines from the original report.', '她引用了原报告中的两行。')],
        [('quote from', '引用……的话')],
    ),
    'quantify': (
        'quant（多少）+ -ify（使）',
        'quantus 是拉丁语「多大、多少」：把程度变成数字，即量化。',
        'quantify 的宾语是「影响、收益、风险」这类抽象事物。',
        [('Quantify your progress: words per day, not feelings.', '把进步量化：每天多少词，而不是凭感觉。')],
        [('quantify the impact', '量化影响')],
    ),
    'segregate': (
        'se-（分开）+ greg（群）',
        'greg 表「群」（如 gregarious、aggregate）：从群里分出去，即隔离、分开。',
        'segregate A from B；日常更常说 separate A from B。',
        [('Segregate the words you know from the ones you do not.', '把会的词和不会的词分开。')],
        [('segregate from', '与……分开')],
    ),
    'state': (
        'st（站立）+ -ate',
        'st 表「站」（如 stable、constant）：站定的样子即「状态」；说出来即「陈述」。',
        'state 名词「状态 / 国家」，动词「陈述」；statement 是「陈述、声明」。',
        [('State your conclusion in the first sentence.', '把结论写在第一句。')],
        [('state a conclusion', '陈述结论')],
    ),
    'undermine': (
        'under（在……之下）+ mine（挖掘）',
        '在下面挖空地基，即逐渐削弱、损害。',
        'undermine 强调「暗暗地、逐渐地削弱」，不是一次性摧毁。',
        [('Skipping sleep undermines everything you revised.', '不睡觉会削弱你复习的一切。')],
        [('undermine confidence', '削弱信心')],
    ),
    'undertake': (
        'under（在……之下）+ take（承担）',
        '把事情担到自己身上，即着手做、承担。',
        'undertake 是及物：undertake a task / study，不加 about。',
        [('She undertook a full review of the reading list.', '她着手全面梳理了阅读清单。')],
        [('undertake a study', '开展研究')],
    ),
    'volunteer': (
        'volunt（意愿）+ -eer',
        'voluntas 是拉丁语「意愿」：出于自愿的人，即志愿者；作动词「自愿做」。',
        'volunteer to do sth. / volunteer for sth.。',
        [('Two students volunteered to check the data.', '两名学生自愿核对数据。')],
        [('volunteer to do', '自愿做')],
    ),
    'witness': (
        'wit（知道）+ -ness',
        'wit 表「知道、看见」（如 wit、aware）：亲眼知道的人，即目击者；作动词「目睹」。',
        'witness 作动词时主语常是「时间、地点」：The decade witnessed…',
        [('The past decade witnessed a shift in teaching methods.', '过去十年见证了教学方法的转变。')],
        [('witness a change', '见证变化')],
    ),
    'yield': (
        'yield（回报、产出）',
        '源自古英语 gieldan「支付、回报」，即产生（结果）、让出。',
        'yield to（屈服于 / 让行）；yield results（产生结果）。',
        [('Twenty minutes a day yields better results than Sunday marathons.', '每天二十分钟比周日突击更有效。')],
        [('yield results', '产生结果')],
    ),
    'summarize': (
        'summ（总和、要点）+ -arize',
        'summa 是拉丁语「总和、要点」：抓出要点，即总结。',
        'summarize 后直接接宾语，不加 about（不说 summarize about the text）。',
        [('Summarize each chapter in two sentences.', '用两句话总结每一章。')],
        [('summarize a text', '总结文本')],
    ),
    'superior': (
        'super（在上方）+ -ior（比较级后缀）',
        'super 表「上」（如 supervise、superficial）：在上面，即更好的、上级。',
        'superior to（优于），介词用 to，不用 than。',
        [('This method proved superior to rote repetition.', '这个方法被证明优于死记硬背。')],
        [('superior to', '优于')],
    ),
    'supervise': (
        'super-（在上方）+ vis（看）',
        'vis / vid 表「看」（如 revise、visible）：在上面看着，即监督、指导。',
        'supervise 强调「边看边指导」，monitor 只是「监视」。',
        [('A tutor supervises the lab session every Friday.', '每周五有导师指导实验课。')],
        [('supervise a project', '指导项目')],
    ),
}

if __name__ == '__main__':
    insert_batch(ENTRIES, 'batch-5', '高频词第四批（re-/sub-/trans- 族与常用抽象词）')
